---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04
    lifecycle:
      pre_converge:
      - remote: sudo apt-get -y update

  - name: centos-6
    driver_config:
      image: centos:centos6

suites:
  - name: lcd_web
    run_list:
      - recipe[test_wrapper::lcd_web]
    verifier:
      inspec_tests:
        - test/integration/default/lcd_web_test
    attributes:
    includes:
      - ubuntu-16.04 

  - name: centos
    run_list:
      - recipe[test_wrapper::lcd_web]
    verifier:
      inspec_tests:
        - test/integration/default/lcd_web_test.rb
    includes:
      - centos-6
    

transport:
#  compression: true 
#  connection_timeout: 5
#  ssh_key: ~/Downloads/pbradford_aws.pem
 